# Generated by Django 5.2.4 on 2025-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('imagen_url', models.URLField()),
            ],
        ),
    ]
